import {chromium} from 'playwright';import assert from 'node:assert/strict';import{writeFileSync}from'node:fs';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--use-angle=swiftshader']});const p=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));const read=()=>p.evaluate(()=>window.worldDiagnostics.state());const check=(n,v)=>{assert.ok(v,n);checks.push(n);console.log('PASS',n)};const click=async(x,y,z)=>{const point=await p.evaluate(([x,y,z])=>window.worldDiagnostics.project(x,y,z),[x,y,z]);await p.mouse.click(point.x,point.y);await p.waitForTimeout(500)};
try{
await p.goto('http://127.0.0.1:5173');await p.waitForFunction(()=>window.worldDiagnostics);await p.waitForTimeout(2000);await p.getByRole('button',{name:'暂停游戏',exact:true}).click();let before=await read();
await p.keyboard.press('1');await p.getByRole('tab',{name:'扩地+'}).click();await p.locator('.drawer').getByRole('button',{name:/开垦大陆/}).click();await p.waitForTimeout(1600);await click(6,.075,0);await p.getByRole('button',{name:'确认建造',exact:true}).click();check('扩张真实增加9格土地并扣除300金币',(await read()).w.tiles.overworld.length===10&&Math.abs(before.r.currency-(await read()).r.currency-300)<.01);await p.waitForTimeout(1400);
await click(-2,.55,-2);await p.getByRole('button',{name:/金币 · 升级/}).click();check('升级住宅提高建筑等级',(await read()).b.buildings.find(b=>b.type==='house').level===2);await p.getByRole('button',{name:/换个位置/}).click();await p.waitForTimeout(1500);await p.keyboard.press('r');await click(-3,.045,-2);let home=(await read()).b.buildings.find(b=>b.type==='house');check('搬迁保留建筑ID并支持旋转',home.x===-3&&home.rotation===1);await p.waitForTimeout(1200);await click(-3,.55,-2);await p.getByRole('button',{name:'拆除',exact:true}).click();await p.getByRole('button',{name:'确认拆除',exact:true}).click();check('拆除住宅清除住户引用',(await read()).n.npcs.every(n=>n.home===''));
await p.getByRole('button',{name:'保存世界',exact:true}).click();const good=await p.evaluate(()=>JSON.parse(localStorage.getItem('kuai-block-save-v2')));await p.getByRole('button',{name:'世界设置',exact:true}).click();await p.getByRole('button',{name:'存档管理',exact:true}).click();const bad=structuredClone(good);bad.town.ledger.sales='not-a-number';const file=p.locator('input[type=file]');await file.setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await p.waitForTimeout(400);check('损坏日报存档被拒绝且不覆盖当前世界',(await p.locator('.toast').innerText()).includes('导入失败')&&(await read()).r.currency===good.resources.currency);
await file.setInputFiles({name:'good.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(good))});await p.waitForTimeout(400);check('有效v2 JSON可以导入',(await p.locator('.toast').innerText()).includes('世界已恢复'));await p.getByRole('button',{name:'关闭设置',exact:true}).click();
const legacy=structuredClone(good);legacy.version=1;delete legacy.town;for(const r of ['wheat','flour','bread','furniture'])delete legacy.resources.bag[r];legacy.npcs=legacy.npcs.map(n=>{for(const k of ['age','family','home','income','wallet','happiness','health','needs','state','destination','likes','recent','lastPurchase'])delete n[k];return n});const context=await browser.newContext();await context.addInitScript(data=>localStorage.setItem('kuai-block-save-v1',JSON.stringify(data)),legacy);const old=await context.newPage();await old.goto('http://127.0.0.1:5173');await old.waitForFunction(()=>window.worldDiagnostics);await old.waitForTimeout(1600);const migrated=await old.evaluate(()=>window.worldDiagnostics.state());check('v1存档迁移保留金币、地块、居民并补齐新字段',migrated.town.legacy&&migrated.r.currency===good.resources.currency&&migrated.w.tiles.overworld.length===10&&migrated.n.npcs.every(n=>n.needs&&n.wallet>=0)&&migrated.r.bag.flour===0);await context.close();check('管理与迁移流程无浏览器错误',errors.length===0);writeFileSync('test-results/management.json',JSON.stringify({checks,errors},null,2));
}finally{await browser.close()}

