import test from 'node:test';
import assert from 'node:assert/strict';
import {simulateTown,metrics,questProgress} from '../src/game/TownSimulation.ts';
import {settlementBuildings,settlementTiles,settlementNpcs,makeCitizen} from '../src/data/settlement.ts';
import {emptyBag,initialTown,emptyFacility} from '../src/data/town.ts';
import {defs} from '../src/data/definitions.ts';
const building=(type,x,z,i=type)=>({id:i,type,x,z,world:'overworld',level:1,rotation:0,born:0});
function start(){const buildings=settlementBuildings();return{town:initialTown(),buildings,npcs:settlementNpcs(buildings),bag:{...emptyBag(),wood:30,food:20},currency:1000,tick:0,weather:[]}}
function run(s,n){for(let i=0;i<n;i++)s=simulateTown(s);return s}
test('新局从 12×9 小大陆、1000 金币、2 位居民开始',()=>{const s=start();assert.equal(settlementTiles().overworld.length,12);assert.equal(s.npcs.length,2);assert.equal(s.currency,1000);assert.equal(metrics(s.buildings,s.npcs,s.bag).capacity,2)});
test('没有空房时人口不增长；住宅和岗位允许新居民入住',()=>{let s=start();s.buildings.push(building('farm',-2,0));assert.equal(run(s,80).npcs.length,2);s.buildings.push(building('house',-3,0,'newhouse'));s=run(s,100);assert.ok(s.npcs.length>2);assert.ok(s.npcs.length<=4);assert.ok(s.npcs.every(n=>n.home));});
test('员工在白天工作，生产进入真实库存',()=>{let s=start();s.buildings.push(building('farm',-2,0));s=run(s,80);assert.ok(s.bag.wheat>0);assert.ok(s.town.ledger.produced.wheat>0);assert.equal(s.npcs.filter(n=>n.workplace).length,2)});
test('原料不足时面包房暂停；补足面粉后消耗原料产出面包',()=>{let s=start();s.town.minute=500;const b=building('bakery',-2,0);s.buildings.push(b);s=run(s,20);assert.equal(s.town.facilities[b.id].status,'缺少原料');assert.equal(s.bag.bread,0);s.bag.flour=2;s=run(s,25);assert.equal(s.bag.flour,0);assert.equal(s.bag.bread,4);});
test('居民消费减少商品和钱包余额，形成营业额与成本',()=>{let s=start();s.town.minute=600;const b=building('shop',-2,0);s.buildings.push(b);s.npcs.forEach(n=>{n.needs.food=50;n.wallet=100});s=run(s,8);const f=s.town.facilities[b.id];assert.ok(f.customers>0);assert.equal(s.town.totalSales,f.customers);assert.ok(f.revenue>0&&f.costs>0);assert.ok(s.town.ledger.consumed.food>0);assert.ok(s.npcs.some(n=>n.wallet<95));assert.ok(s.bag.food<20);});
test('无人消费的店铺仍有成本，可以真实亏损',()=>{let s=start();s.town.minute=500;s.buildings=s.buildings.filter(b=>b.type!=='house');s.buildings.push(building('shop',-2,0));s.npcs.forEach(n=>{n.wallet=0;n.needs.food=0});const initial=s.currency;s=run(s,10);assert.ok(s.currency<initial);assert.equal(s.town.totalSales,0)});
test('公园改善幸福与环境；食物短缺和失业降低幸福',()=>{let s=start();s.town.minute=1100;s.npcs.forEach(n=>n.needs.fun=80);const bad=run({...s,bag:emptyBag()},60);const good=start();good.town.minute=1100;/* 公园须在初始住宅(-2,-2)三格内，远处公园不再全图消除娱乐需求。 */good.buildings.push(building('park',-3,-2));good.npcs.forEach(n=>n.needs.fun=80);const improved=run(good,60);assert.ok(improved.town.metrics.environment>bad.town.metrics.environment);assert.ok(improved.town.metrics.happiness>bad.town.metrics.happiness)});
test('每日结算收入减成本等于净利润，不强制暂停',()=>{let s=start();s.town.minute=1436;s.town.ledger.revenue=100;s.town.ledger.wages=20;s.town.ledger.maintenance=8;s.town.ledger.purchases=12;s=run(s,1);assert.equal(s.town.day,2);assert.equal(s.town.reports[0].profit,60);assert.equal(s.town.minute,0)});
test('同一状态得到相同事件，事件有持续时间并影响生产',()=>{const s=start();s.town.nextEvent=1;const a=run(s,1),b=run(s,1);assert.deepEqual(a,b);assert.equal(a.town.events.length,1);assert.equal(run(a,65).town.events.length,0);let base=start();base.town.minute=480;base.buildings.push(building('farm',-2,0));let rain=structuredClone(base);rain.weather=['rain'];const normal=run(base,31),wet=run(rain,31);assert.ok(normal.bag.wheat>wet.bag.wheat);});
test('愿望依据真实建造和人口达成，解锁等级保留',()=>{let s=start();s.town.builtCounts.house=1;s=run(s,1);assert.ok(s.town.completed.includes('welcome-home'));assert.equal(questProgress(s.town,s.buildings,'welcome-home'),1);s.buildings.push(building('house',-3,0,'h2'),building('house',-4,0,'h3'));for(let i=2;i<6;i++)s.npcs.push(makeCitizen(`n${i}`,i,i<4?'h2':'h3'));s=run(s,1);assert.equal(s.town.level,1);assert.equal(s.town.upgradeReady,true);s.town.level=2;s.town.upgradeReady=false;s.npcs=s.npcs.slice(0,2);s=run(s,1);assert.equal(s.town.level,2)});
test('完整 5 分钟闭环：入住、麦田、面粉、面包、消费与经营结算',()=>{let s=start();const types=[['house',-3,0],['house',-4,0],['house',1,0],['house',3,0],['farm',-2,0],['lumber',1,-2],['windmill',-1,-2],['bakery',-3,-2],['shop',2,0],['breadshop',-1,0]];types.forEach(([type,x,z],i)=>s.buildings.push(building(type,x,z,'placed'+i)));s=run(s,300);assert.ok(s.npcs.length>=6,`居民 ${s.npcs.length}`);assert.ok(s.town.totalSales>0);assert.ok((s.town.ledger.produced.bread||0)+(s.town.reports[0]?.produced.bread||0)>0,'面包产业链未运转');assert.ok(s.town.reports.length>0);assert.ok(s.town.ledger.wages + s.town.reports[0].wages > 0);console.log('5分钟经营实测',JSON.stringify({population:s.npcs.length,sales:s.town.totalSales,coins:Math.round(s.currency),level:s.town.level,happiness:Math.round(s.town.metrics.happiness)}));});
test('长期经营：五天后仍有食品消费、家庭购买力和可盈利日报',()=>{let s=start();s.buildings.push(building('house',-3,-2,'h2'),building('house',-3,0,'h3'),building('farm',-2,0,'f1'),building('farm',1,0,'f2'),building('windmill',-1,-2),building('bakery',1,-2),building('shop',-1,0),building('breadshop',2,0),building('park',3,0));for(let i=2;i<6;i++)s.npcs.push(makeCitizen('n'+i,i,i<4?'h2':'h3'));s=run(s,1800);assert.ok(s.town.reports[0].sales>0);assert.ok(s.town.reports.some(r=>r.profit>0),'合理布局应有盈利日');assert.ok(s.npcs.every(n=>Number.isFinite(n.wallet)&&n.wallet>=0));assert.ok(s.town.metrics.happiness>45);console.log('五天经济',s.town.reports.map(r=>({day:r.day,sales:r.sales,profit:Math.round(r.profit)})))});
test('流感真实损害健康，诊所员工可减轻影响',()=>{let base=start();base.town.events=[{id:'flu-test',type:'flu',title:'流感',description:'',remaining:65,duration:65}];let clinic=structuredClone(base);clinic.buildings.push(building('clinic',-2,0));const a=run(base,40),b=run(clinic,40);assert.ok(b.town.metrics.health>a.town.metrics.health);});
test('商店食品计入供给，过高售价不会成交',()=>{let s=start();s.town.minute=500;s.buildings.push(building('shop',-2,0));s.town.facilities.shop={...emptyFacility(),stock:12,priceFactor:1.8};s.bag.food=0;s.npcs.forEach(n=>n.needs.food=70);s=run(s,10);assert.equal(s.town.totalSales,0);assert.ok(s.town.metrics.foodDays>=3)});
