import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
mkdirSync('test-results',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--use-angle=swiftshader','--enable-webgl']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
const state=()=>page.evaluate(()=>window.worldDiagnostics.state());
const check=(name,ok)=>{assert.ok(ok,name);checks.push(name);console.log('PASS',name)};
async function clickWorld(x,y,z){const pos=await page.evaluate(([x,y,z])=>window.worldDiagnostics.project(x,y,z),[x,y,z]);await page.mouse.click(pos.x,pos.y);await page.waitForTimeout(350)}
async function build(category,name,x,z){await page.locator('.build-categories button').filter({hasText:category}).click();await page.waitForTimeout(350);const card=page.locator('.facility').filter({has:page.getByRole('heading',{name,exact:true})});await card.getByRole('button',{name:/建造/}).click();await page.waitForTimeout(1400);const before=(await state()).b.buildings.length;await clickWorld(x,.045,z);const after=await state();check(`实际鼠标建造 ${name}`,after.b.buildings.length===before+1);await page.keyboard.press('Escape')}
async function claim(){await page.getByRole('button',{name:'邻里愿望',exact:true}).click();await page.waitForTimeout(200);const buttons=page.getByRole('button',{name:'领取奖励',exact:true});while(await buttons.count())await buttons.first().click();await page.keyboard.press('Escape');await page.waitForTimeout(1000)}
try{
 await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>window.worldDiagnostics);await page.waitForTimeout(2200);await page.getByRole('button',{name:'暂停游戏',exact:true}).click();let s=await state();check('小镇新局：9块土地，2位居民，1000金币',s.w.tiles.overworld.length===9&&s.n.npcs.length===2&&s.r.currency>=1000&&s.r.currency<1002);await page.screenshot({path:'test-results/town-start.png'});
 await build('住宅','小木屋',-3,-2);await build('生产','麦穗农田',-2,0);await build('商业','邻里杂货店',-1,0);await build('生产','林间伐木场',1,0);await build('生产','谷风磨坊',-1,-2);await build('住宅','小木屋',-3,0);
 s=await state();check('建造真实扣除金币和木材',s.r.currency<201&&s.r.bag.wood===20);await page.getByRole('button',{name:'4倍速',exact:true}).click();await page.waitForFunction(()=>window.worldDiagnostics.state().town.completed.length>=3,{},{timeout:15000});await claim();check('愿望奖励实际到账',(await state()).r.currency>300);
 await page.waitForFunction(()=>window.worldDiagnostics.state().n.npcs.length>=6,{},{timeout:65000});s=await state();check('住房和岗位吸引6位居民，解锁Lv2',s.town.level===2);check('居民真实就业、食物生产与店铺销售',s.town.metrics.employed>0&&s.town.totalSales>0&&s.town.ledger.produced.wheat>0);await claim();
 await page.getByRole('button',{name:'暂停游戏',exact:true}).click();await build('生产','小镇面包房',1,-2);await build('商业','猫猫面包店',2,0);await page.getByRole('button',{name:'4倍速',exact:true}).click();await claim();
 await page.getByRole('button',{name:'居民与供需',exact:true}).click();await page.waitForTimeout(500);await page.screenshot({path:'test-results/town-residents.png'});await page.locator('.resident').first().click();check('居民详情有住所、需求、钱包和家庭收入',(await page.locator('.drawer').innerText()).includes('家庭汇款'));await page.keyboard.press('Escape');
 await page.waitForFunction(()=>{const t=window.worldDiagnostics.state().town;return(t.ledger.produced.bread||0)+t.reports.reduce((n,r)=>n+(r.produced.bread||0),0)>0},{},{timeout:100000});check('完整面包链在实际运行时产出',true);
 await page.getByRole('button',{name:'暂停游戏',exact:true}).click();await page.waitForTimeout(1200);s=await state();await page.waitForTimeout(1300);check('暂停停止所有经营计时',(await state()).g.ticks===s.g.ticks);
 await page.getByRole('button',{name:'小镇日报',exact:true}).click();await page.waitForTimeout(500);check('日报包含经营成本、销售与事件',(await page.locator('.drawer').innerText()).includes('采购成本'));await page.screenshot({path:'test-results/town-daily.png'});await page.keyboard.press('Escape');await page.waitForTimeout(1200);
 await clickWorld(-1,.5,0);await page.waitForTimeout(500);check('建筑详情显示真实库存与经营数据',(await page.locator('.drawer').innerText()).includes('售价系数'));await page.screenshot({path:'test-results/town-shop.png'});await page.getByRole('button',{name:'暂停营业',exact:true}).click();check('可暂停店铺经营',(await state()).b.buildings.some(b=>b.type==='shop'&&b.paused));await page.getByRole('button',{name:'恢复营业',exact:true}).click();await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'保存世界',exact:true}).click();const saved=await state();await page.reload();await page.waitForFunction(()=>window.worldDiagnostics);await page.waitForTimeout(2000);s=await state();check('v2存档恢复人口、建筑、库存、任务和金币',s.n.npcs.length===saved.n.npcs.length&&s.b.buildings.length===saved.b.buildings.length&&s.r.currency===saved.r.currency&&s.town.claimed.length===saved.town.claimed.length);
 await page.screenshot({path:'test-results/town-developed.png'});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1800);check('手机布局没有横向溢出',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-results/town-mobile.png'});await page.getByRole('button',{name:'居民与供需',exact:true}).click();await page.waitForTimeout(450);check('手机可打开经营面板',await page.locator('.drawer').isVisible());await page.screenshot({path:'test-results/town-mobile-panel.png'});check('运行期间没有浏览器异常',errors.length===0);
 writeFileSync('test-results/town-browser.json',JSON.stringify({checks,errors,state:s},null,2));
} catch(e){await page.screenshot({path:'test-results/town-failure.png'});console.log('STATE',JSON.stringify(await state()));throw e}finally{await browser.close()}
